[phases.setup]
  nixPkgs = ["nodejs_20"]
  cmds = ["npm install -g pnpm@9"]

[phases.install]
  cmds = ["pnpm install --frozen-lockfile"]
  dependsOn = ["setup"]

[phases.build]
  cmds = ["pnpm build"]
  dependsOn = ["install"]

[start]
  cmd = "pnpm start:prod"
